# Generated by Django 2.2 on 2022-03-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_typeclothes_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('collection', models.CharField(default='', max_length=50)),
                ('material', models.CharField(default='', max_length=50)),
                ('size', models.CharField(default='', max_length=50)),
                ('color', models.CharField(default='', max_length=50)),
                ('image', models.TextField(default='https://assets.vogue.com/photos/62274b72c0d4fbe60f143e7e/master/w_2560%2Cc_limit/00001-chanel-fall-2022-ready-to-wear-paris-credit-gorunway.jpg', max_length=255)),
                ('brandClothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.BrandClothes')),
                ('typeClothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.TypeClothes')),
            ],
        ),
    ]
