# Generated by Django 2.2 on 2022-03-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_clothes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothes',
            new_name='ClothesA',
        ),
    ]
