# Generated by Django 2.2 on 2022-03-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20220321_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('inventory', models.IntegerField(default=0)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.ClothesA')),
            ],
        ),
    ]
