# Generated by Django 2.2 on 2022-04-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Fast'), (3, 'Take away')], default=2)),
                ('address', models.CharField(default='', max_length=50)),
                ('codShip', models.TextField(default='', max_length=50)),
            ],
        ),
    ]
