# Generated by Django 2.2 on 2022-03-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.TextField(default='https://cdn5.f-cdn.com/contestentries/1840252/39964678/5fa3d8364496e_thumb900.jpg', max_length=255)),
                ('storage', models.IntegerField(default=0)),
                ('screensize', models.CharField(default='', max_length=50)),
                ('ram', models.TextField(default='', max_length=50)),
                ('chip', models.TextField(default='', max_length=50)),
                ('os', models.TextField(default='', max_length=50)),
            ],
        ),
    ]
