# Generated by Django 2.2 on 2022-03-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
