# Generated by Django 2.2 on 2022-03-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephone', '0002_mobilephone_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobilePhone',
            new_name='MobilePhoneA',
        ),
    ]
