# Generated by Django 2.2 on 2022-03-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephone', '0003_auto_20220321_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephonea',
            name='image',
            field=models.TextField(default='https://cdn-amz.fadoglobal.io/images/I/71hIfcIPyxS.jpg', max_length=255),
        ),
    ]
