# Generated by Django 2.2 on 2022-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220414_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_no',
            field=models.TextField(default='Order', max_length=255),
        ),
    ]
