# Generated by Django 2.2 on 2022-05-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_no',
            field=models.TextField(default='Order default', max_length=255),
        ),
    ]
