# Generated by Django 2.2 on 2022-05-03 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipmencost'),
        ('cart', '0005_auto_20220503_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='orderId',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shipment.Shipment'),
        ),
    ]
