# Generated by Django 2.2 on 2022-05-03 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20220503_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_no',
        ),
    ]
