# Generated by Django 2.2 on 2022-05-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20220503_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerId',
            field=models.IntegerField(default=1),
        ),
    ]
