# Generated by Django 2.2 on 2022-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentId',
            field=models.IntegerField(default=2),
        ),
    ]
